# -*- coding: utf-8 -*-
"""py teste

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xo5ES_HySQqvgXboo0Q4hPS6s6DzDA_7
"""

from datetime import date

class Funcionario:
    def __init__(self,nome,dataNascimento, salario):
      self._nome = nome
      self._dataNascimento = dataNascimento
      self._salario = salario

    @property
    def nome(self):
      return self._nome

    @property
    def salario(self):
      return self._salario

    def idade(self):
      lista_dataNasc = self._dataNascimento.split("/")
      ano = lista_dataNasc[-1]
     

      ano_atual = date.today().year

      idade = ano_atual - int(ano)

      return idade





    def calcular_bonus(self):
      valor = self._salario*0.1
      if valor >1000:
        valor = 0
      
      return valor

    
    def __str__(self):
      return f" Funcionario {self._nome} - Nascimento {self._dataNascimento} - Salário {self._salario}"

vini = Funcionario("Vini Dias", "27/10/2003", 8000)
print(vini)
print(vini.idade())